# Calculating our grades

We store percentages (such as the __weight__ of each assignment type) as a number between 0 and 1. So 0% is 0, 50% is .50, 75% is 0.75, and 1.00 is 100%. 

Lets take the syllabus for a course you may be currently enrolled in: COMM 100C:

* Section Assignments & Participation 30%
* Weekly Assessments 20%
* Midterm 20%
* Final 30%

In [20]:
participation_weight = .30
assignments_weight = .20
midterm_weight = .20
final_weight = .30

Did we get that right? Does it all add up to 1 (that is, 100%)?

In [21]:
participation_weight + assignments_weight + midterm_weight + final_weight

1.0

Now lets set our grades to be:
* Participation: 100%
* Assignments (average across all): 80%
* Midterm: 100%
* Final: 90%

In [22]:
participation_grade = 1.00
assignments_grade = .80
midterm_grade = 1.00
final_grade = .90

Then we can have a big formula that multiplies each grade by the weight, then adds them up:

In [23]:
(participation_grade * participation_weight) + (assignments_grade * assignments_weight) + (midterm_grade * midterm_weight) + (final_grade * final_weight)

0.93

This means our grade would be 93/100.

You can also break lines up to make it more readable using `\` --- if you don't, it will assume each new line is a new instruction

In [24]:
(participation_grade * participation_weight) + \
(assignments_grade * assignments_weight) + \
(midterm_grade * midterm_weight) + \
(final_grade * final_weight)

0.93

### Multiple assignments within a grade category

But typically you have a lot of assignments within a category, like having 10 weekly reflection assignments. So we can do a two-step process of calculating our average (or __mean__) grade for the weekly reflection assignments, then store that as the `assignments_grade`. Then we can re-run that first fomula.

To store lists of numbers, we can use a __list__. In python, we specify we are making a list by putting square brackets around a set of numbers and variables, separated by commas. 

Now, depending on how your individual assignments are graded, you might have to enter them in different ways. If you get back a percentage from 0 to 100, you can just enter that in. So if your assignment grades were 0%, 100%, 20%, 60%, 100%, 60%, 80%, 100%, 100%, and 0, that would be:

In [25]:
assignments_list = [0.0, 1.0, 0.2, 0.6, 1.0, 0.6, 0.8, 1.0, 1.0, 0.0]

But what if your assignments are graded on a scale of 0-5 and our grades were 0, 5, 1, 3, 5, 3, 4, 5, 5, and 0? We can enter them in as fractions, which will automatically be converted to a percentage:

In [26]:
assignments_list = [0/5, 5/5, 1/5, 3/5, 5/5, 3/5, 4/5, 5/5, 5/5, 0/5]
assignments_list

[0.0, 1.0, 0.2, 0.6, 1.0, 0.6, 0.8, 1.0, 1.0, 0.0]

#### Averages with numpy library

One of the great things about python is that people have written all kinds of general-purpose ___libraries___ that you can ___import___ and then use the functions they have created. ___numpy___ is a very powerful and popular library. 

In [8]:
import numpy

In statistics and data science, we use __mean__ instead of __average__. The numpy library can calculate the mean for us:

In [9]:
numpy.mean(assignments_list)

0.62

So lets use the `numpy.mean()` function and store that as `assignments_grade`:

In [10]:
assignments_grade = numpy.mean(assignments_list)
assignments_grade

0.62

So now we can call the formula we had at the beginning of the notebook again. Because we changed `assignments_grade`, that will be updated. But just for our clarity, we will store the other variables for participation, midterm, and final again, even though they should still be in the computer's memory:

In [11]:
participation_grade = 1.00
midterm_grade = 1.00
final_grade = .90
assignments_grade = numpy.mean(assignments_list)

participation_weight = .30
assignments_weight = .20
midterm_weight = .20
final_weight = .30

In [12]:
(participation_grade * participation_weight) + \
(assignments_grade * assignments_weight) + \
(midterm_grade * midterm_weight) + \
(final_grade * final_weight)

0.894

## Dropping the lowest grades

But what about if you have an assignment group where the lowest 1 or 2 grades are dropped? We can use functions to handle that as well. First we need to sort the list from smallest to largest:

In [13]:
assignments_list = numpy.sort(assignments_list)
assignments_list

array([0. , 0. , 0.2, 0.6, 0.6, 0.8, 1. , 1. , 1. , 1. ])

You can ignore the fact that our list is inside this `array()` function.

Then we will remove the first item from the list. There are a lot of ways to do this. One way to do this is to use the ___index selection___ method, which is called with square brackets, instead of parentheses:
`assignments_list[start:end]`. But note that the first item is 0, so the 10th item is actually 9. This is confusing at first, there are lots of memes about starting to count from 0. 

If you don't put a number after the colon, then it goes until the end of the list.

In [14]:
assignments_list[0:]

array([0. , 0. , 0.2, 0.6, 0.6, 0.8, 1. , 1. , 1. , 1. ])

Selecting everything after the first item (dropping lowest):

In [15]:
assignments_list[1:]

array([0. , 0.2, 0.6, 0.6, 0.8, 1. , 1. , 1. , 1. ])

Selecting everything after the first two items (dropping lowest two):

In [16]:
assignments_list[2:]

array([0.2, 0.6, 0.6, 0.8, 1. , 1. , 1. , 1. ])

FYI, when you do a select, the items you don't select are still there in the original list. They aren't deleted:

In [17]:
assignments_list

array([0. , 0. , 0.2, 0.6, 0.6, 0.8, 1. , 1. , 1. , 1. ])

Lets calculate the grade again, but only selecting everything but the lowest grade.

In [18]:
assignments_average = numpy.mean(assignments_list[1:])
assignments_average

0.6888888888888888

And now we can re-run that big function that calculates all the grades:

In [19]:
class_grade = (participation_grade * participation_weight) + \
(assignments_grade * assignments_weight) + \
(midterm_grade * midterm_weight) + \
(final_grade * final_weight)

class_grade

0.894

## Make sure to go to Kernel -> Restart and run all cells and make sure there are no errors